/**
 * Flatten the multi-product Harmony source into a single-product build.
 *
 * Given a product (cp | vp | ppm | maconomy), emits a clean single-product
 * package to dist-products/<product>/:
 *   - tokens.css flattened: the product's html[data-product] block resolved
 *     into :root (+ its .dark into .dark); all other products and every
 *     data-product selector stripped.
 *   - a mode-only theme provider (no setProduct / no runtime product switching).
 *   - components/index.ts filtered to exclude components not available in the
 *     product (per src/data product scope, mirrored here).
 *   - a product-scoped package.json (name suffix -<product>).
 *
 * Usage: node scripts/build-product.mjs <product> [outDir]
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  rmSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateRegistryFromDisk } from './lib/registry.mjs';

const PRODUCTS = ['cp', 'vp', 'ppm', 'maconomy'];

const here = dirname(fileURLToPath(import.meta.url));
const PKG = join(here, '..');

/**
 * Components exclusive to a subset of products (mirrors src/data/component-catalog.ts
 * `componentProducts` in the reference). A component absent here ships in all products.
 * Maps to the export identifiers to strip from components/index.ts for other products.
 */
const PRODUCT_EXCLUSIVE = {
  FloatingNav: { products: ['cp'], exports: ['FloatingNav', 'FloatingNavProps'] },
  KanbanCardCostpoint: { products: ['cp'], exports: ['KanbanCardCostpoint'] },
  TableCostpointGrid: { products: ['cp'], exports: ['TableCostpointGrid'] },
};

function fail(msg) {
  console.error(`build-product: ${msg}`);
  process.exit(1);
}

/** Split a flat CSS file into top-level `{selector, body}` blocks (no nesting). */
function splitTopLevelBlocks(css) {
  const blocks = [];
  let depth = 0;
  let pending = '';
  let body = '';
  let selector = '';
  for (const ch of css) {
    if (ch === '{') {
      if (depth === 0) {
        selector = pending.trim();
        pending = '';
        body = '';
      } else {
        body += ch;
      }
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        blocks.push({ selector, body });
        pending = '';
      } else {
        body += ch;
      }
    } else if (depth === 0) {
      pending += ch;
    } else {
      body += ch;
    }
  }
  return blocks;
}

/** Parse a CSS block body into an ordered map of declarations (comments dropped). */
function parseDeclarations(body, into) {
  const map = into ?? new Map();
  // Strip block comments across the whole body first — a multi-line comment may
  // contain ';' which would otherwise survive a naive per-declaration split.
  const clean = body.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const raw of clean.split(';')) {
    const part = raw.trim();
    if (!part) continue;
    const idx = part.indexOf(':');
    if (idx === -1) continue;
    const key = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (key.startsWith('--')) map.set(key, value); // custom props only; product overrides base in place
  }
  return map;
}

function emitBlock(selector, map) {
  const lines = [...map.entries()].map(([k, v]) => `  ${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

/**
 * Resolve the chosen product into a single clean :root/.dark, dropping every
 * other product and all data-product selectors. Base and product declarations
 * are merged (product wins) so the delivered file reads as one product with no
 * cascade ambiguity — optimized for single-product human/AI consumers.
 */
function flattenTokens(css, product) {
  const blocks = splitTopLevelBlocks(css);
  const root = new Map();
  const dark = new Map();
  const passthrough = [];
  for (const { selector, body } of blocks) {
    const sel = selector.replace(/\/\*[\s\S]*?\*\//g, '').trim();
    if (sel === ':root') {
      parseDeclarations(body, root);
      continue;
    }
    if (sel === 'html.dark' || sel === '.dark') {
      parseDeclarations(body, dark);
      continue;
    }
    const m = sel.match(/^html\[data-product=['"]([a-z]+)['"]\](\.dark)?$/);
    if (m) {
      if (m[1] === product) parseDeclarations(body, m[2] ? dark : root);
      continue; // other products dropped
    }
    passthrough.push(`${selector.trim()} {${body}}`); // @media etc. kept verbatim
  }
  const parts = [
    `/* Harmony single-product build: ${product}. Generated by build-product.mjs — do not edit.`,
    `   Product is baked into :root/.dark; there is no product attribute or runtime switching. */`,
    '',
    emitBlock(':root', root),
  ];
  if (dark.size) parts.push('', emitBlock('.dark', dark));
  if (passthrough.length) parts.push('', ...passthrough);
  return parts.join('\n') + '\n';
}

/**
 * Resolve component-level product arbitrary variants (`[[data-product=P]_&]:x`).
 * For the chosen product: make them unconditional (strip the guard). For other
 * products: remove the class entirely. Keeps single-product components free of
 * runtime product concepts.
 */
function rewriteProductVariants(root, product) {
  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (/\.(tsx?|jsx?)$/.test(entry)) files.push(full);
    }
  };
  walk(root);
  const keepRe = new RegExp(`\\[\\[data-product=${product}\\]_&\\]:`, 'g');
  // Match the guard prefix + its utility, stopping before any string delimiter or
  // whitespace so we never swallow the closing quote/comma of the containing literal.
  const dropRe = /\[\[data-product=[a-z]+\]_&\]:[^\s'"`]+/g;
  for (const file of files) {
    const src = readFileSync(file, 'utf8');
    if (!src.includes('[[data-product=')) continue;
    const next = src
      .replace(keepRe, '')
      .replace(dropRe, '')
      .replace(/'[ ]+'/g, "''") // tidy strings left all-spaces by removals
      .replace(/' {2,}/g, "' ")
      .replace(/ {2,}'/g, " '");
    if (next !== src) writeFileSync(file, next);
  }
}

/** Mode-only theme provider: product baked, no setProduct / no runtime switching. */
function modeOnlyProvider(product, meta) {
  const productName = JSON.stringify(meta.name);
  const logoSrc = JSON.stringify(meta.logo);
  return `import {
  createContext,
  useCallback,
  useContext,
  useLayoutEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';

/* Single-product build: '${product}'. Product is fixed at build time — there is
   no runtime product switching. Only light/dark mode is a runtime concern.
   Brand identity (name + logo) is baked in from product-meta.json. */
export type HarmonyProduct = '${product}';
export type HarmonyMode = 'light' | 'dark';

export interface HarmonyThemeContextValue {
  product: HarmonyProduct;
  mode: HarmonyMode;
  /** Display name of this product (baked at build time). */
  productName: string;
  /** Logo of this product as a data URI (baked at build time). */
  logoSrc: string;
  setMode: (mode: HarmonyMode) => void;
  toggleMode: () => void;
}

const PRODUCT: HarmonyProduct = '${product}';
const PRODUCT_NAME = ${productName};
const PRODUCT_LOGO = ${logoSrc};
const HarmonyThemeContext = createContext<HarmonyThemeContextValue | null>(null);
const STORAGE_MODE = 'harmony-shadcn-mode';

function readStoredMode(): HarmonyMode {
  if (typeof window === 'undefined') return 'light';
  const v = window.localStorage.getItem(STORAGE_MODE);
  return v === 'dark' ? 'dark' : 'light';
}

export interface HarmonyThemeProviderProps {
  children: ReactNode;
  defaultMode?: HarmonyMode;
}

export function HarmonyThemeProvider({ children, defaultMode }: HarmonyThemeProviderProps) {
  const [mode, setModeState] = useState<HarmonyMode>(() => defaultMode ?? readStoredMode());

  useLayoutEffect(() => {
    document.documentElement.classList.toggle('dark', mode === 'dark');
    window.localStorage.setItem(STORAGE_MODE, mode);
  }, [mode]);

  const setMode = useCallback((m: HarmonyMode) => setModeState(m), []);
  const toggleMode = useCallback(() => setModeState((m) => (m === 'light' ? 'dark' : 'light')), []);

  const value = useMemo(
    () => ({
      product: PRODUCT,
      mode,
      productName: PRODUCT_NAME,
      logoSrc: PRODUCT_LOGO,
      setMode,
      toggleMode,
    }),
    [mode, setMode, toggleMode],
  );

  return <HarmonyThemeContext.Provider value={value}>{children}</HarmonyThemeContext.Provider>;
}

export function useHarmonyTheme(): HarmonyThemeContextValue {
  const ctx = useContext(HarmonyThemeContext);
  if (!ctx) throw new Error('useHarmonyTheme must be used within HarmonyThemeProvider');
  return ctx;
}

/** Null-safe variant used by shell pieces so they render without a provider. */
export function useHarmonyThemeOptional(): HarmonyThemeContextValue | null {
  return useContext(HarmonyThemeContext);
}
`;
}

/**
 * Make the icon subsystem product-less for the delivered build: prune the
 * icon manifest to just this product's flat name->entry map, and rewrite
 * resolveManifestIcon so it no longer takes (or needs) a product. Icon.tsx keeps
 * working unchanged because the mode-only provider still exposes the baked product.
 */
function productlessIcon(outDir, product) {
  const manifestPath = join(outDir, 'src', 'data', 'icon-manifest.json');
  const full = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const scoped = full[product] ?? {};
  writeFileSync(manifestPath, JSON.stringify(scoped, null, 2) + '\n');

  const resolvePath = join(outDir, 'src', 'components', 'icon', 'resolveManifestIcon.ts');
  writeFileSync(
    resolvePath,
    `import iconManifest from '../../data/icon-manifest.json';

export type ManifestIconSource = 'hero' | 'tabler' | 'custom';

export interface ManifestIconEntry {
  source: ManifestIconSource;
  path?: string;
  svg?: string;
}

const manifest = iconManifest as Record<string, ManifestIconEntry>;

/* Single-product build: the manifest is already scoped to '${product}', so there
   is no product to resolve. The optional second arg is ignored and kept only for
   source-compatibility with the multi-product reference. */
export function resolveManifestIcon(name: string, _product?: string): ManifestIconEntry | null {
  return manifest[name] ?? null;
}
`,
  );
}

/** Remove excluded components' export identifiers from a components/index.ts source. */
function filterComponentIndex(indexPath, excludedIdents) {
  if (excludedIdents.size === 0) return;
  const src = readFileSync(indexPath, 'utf8');
  const kept = src
    .split('\n')
    .filter((line) => {
      const ident = line
        .trim()
        .replace(/^type\s+/, '')
        .replace(/,\s*$/, '')
        .trim();
      return !excludedIdents.has(ident);
    })
    .join('\n');
  writeFileSync(indexPath, kept);
}

/** Prepend a single-product banner to an AI artifact so agents know the fixed product. */
function prependProductBanner(path, product, kind) {
  const P = product.toUpperCase();
  const lines = [
    `Harmony Design System (shadcn) — ${P} single-product build.`,
    '',
    `This package is a fixed, single-product build for ${P}. Product is chosen at`,
    'install time and cannot change at runtime. Treat this as a plain',
    'shadcn + Tailwind + Radix component library:',
    `  - There is NO product switching. HarmonyThemeProvider only toggles light/dark`,
    '    mode (defaultMode); it takes no product prop.',
    '  - Do not set data-product, defaultProduct, or reason about other products.',
    `  - Field geometry, density, and tokens are already baked for ${P}.`,
    '  - Components not available in this product are not exported here.',
    '',
    'For light/dark only:',
    "  <HarmonyThemeProvider defaultMode=\"light\">…</HarmonyThemeProvider>",
    '',
    '---',
    '',
  ];
  const banner = kind === 'md' ? `<!--\n${lines.join('\n')}\n-->\n\n` : `${lines.join('\n')}\n\n`;
  writeFileSync(path, banner + readFileSync(path, 'utf8'));
}

function main() {
  const product = process.argv[2];
  if (!product || !PRODUCTS.includes(product)) {
    fail(`product must be one of ${PRODUCTS.join(', ')}`);
  }
  const outDir = process.argv[3] || join(PKG, 'dist-products', product);

  // 1. Copy source tree, then overwrite the product-specific parts.
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  cpSync(join(PKG, 'src'), join(outDir, 'src'), { recursive: true });

  // 2. Flatten tokens.
  const tokens = readFileSync(join(PKG, 'src', 'styles', 'tokens.css'), 'utf8');
  writeFileSync(join(outDir, 'src', 'styles', 'tokens.css'), flattenTokens(tokens, product));

  // 2b. Resolve + prune product metadata (name + logo) to just this product, so
  //     no other-product brand ships. build bakes the resolved values into the
  //     provider; the pruned JSON keeps product-meta.ts valid for the fallback.
  const metaAll = JSON.parse(readFileSync(join(PKG, 'src', 'data', 'product-meta.json'), 'utf8'));
  const rawMeta = metaAll[product];
  if (!rawMeta) fail(`product-meta.json has no entry for '${product}'`);
  const meta = {
    name: rawMeta.name,
    logo: `data:image/svg+xml;utf8,${encodeURIComponent(rawMeta.svg)}`,
  };
  writeFileSync(
    join(outDir, 'src', 'data', 'product-meta.json'),
    JSON.stringify({ [product]: rawMeta }, null, 2) + '\n',
  );

  // 3. Mode-only provider (brand baked in).
  writeFileSync(join(outDir, 'src', 'theme', 'index.tsx'), modeOnlyProvider(product, meta));

  // 3b. Resolve component-level product arbitrary variants for this product.
  rewriteProductVariants(join(outDir, 'src', 'components'), product);
  rewriteProductVariants(join(outDir, 'src', 'layouts'), product);

  // 4. Filter product-excluded component exports.
  const excludedIdents = new Set();
  for (const def of Object.values(PRODUCT_EXCLUSIVE)) {
    if (!def.products.includes(product)) {
      for (const e of def.exports) excludedIdents.add(e);
    }
  }
  filterComponentIndex(join(outDir, 'src', 'components', 'index.ts'), excludedIdents);

  // 4b. Product-less icon subsystem (pruned manifest, product-free resolver).
  productlessIcon(outDir, product);

  // 5. Copy + product-specialize the AI/consumer artifacts.
  for (const artifact of ['AGENTS.md', 'llms.txt']) {
    cpSync(join(PKG, artifact), join(outDir, artifact));
  }
  cpSync(join(PKG, 'docs'), join(outDir, 'docs'), { recursive: true });
  prependProductBanner(join(outDir, 'AGENTS.md'), product, 'md');
  prependProductBanner(join(outDir, 'llms.txt'), product, 'txt');

  // 6. Product-scoped package.json.
  const basePkg = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8'));
  const productName = `${basePkg.name}-${product}`;
  const pkg = {
    ...basePkg,
    name: productName,
    description: `Harmony Design System (shadcn) — ${product.toUpperCase()} single-product build. Product is fixed; no runtime switching.`,
    harmonyProduct: product,
    scripts: { typecheck: 'tsc --noEmit' },
  };
  writeFileSync(join(outDir, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');

  // 7. Regenerate a complete, product-scoped shadcn CLI registry (shims import
  //    from the product package name; excluded components are already dropped
  //    from the filtered components/index.ts).
  generateRegistryFromDisk({
    registryRoot: outDir,
    pkgName: productName,
    componentsIndexPath: join(outDir, 'src', 'components', 'index.ts'),
    name: `harmony-design-system-shadcn-${product}`,
    homepage: basePkg.repository?.url?.replace(/^git\+/, '').replace(/\.git$/, '') ?? '',
  });

  const excludedNote = excludedIdents.size
    ? ` (excluded: ${[...excludedIdents].join(', ')})`
    : '';
  console.log(`build-product: ${product} -> ${outDir}${excludedNote}`);
}

main();
