/**
 * Bundle the design system's fonts into the package so consumers get correct
 * typography from a single stylesheet import — no separate @fontsource setup.
 *
 * For each family it reads the installed @fontsource-variable package, copies
 * the variable woff2 files (latin + latin-ext, normal + italic) into
 * src/styles/fonts/, copies the OFL license, and regenerates src/styles/fonts.css
 * with @font-face rules that use the plain family names referenced by tokens.css
 * ('Figtree', 'Lexend', 'JetBrains Mono'). Run: npm run sync:fonts.
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  rmSync,
  existsSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const PKG = join(here, '..');
const STYLES = join(PKG, 'src', 'styles');
const OUT_FONTS = join(STYLES, 'fonts');

/** Variable @fontsource packages backing each Harmony font-family token. */
const FAMILIES = [
  { pkg: '@fontsource-variable/figtree' },
  { pkg: '@fontsource-variable/lexend' },
  { pkg: '@fontsource-variable/jetbrains-mono' },
];

/** The axis stylesheets to include (normal + italic when the package ships them). */
const AXIS_CSS = ['wght.css', 'wght-italic.css'];

function resolvePkgDir(pkg) {
  return dirname(require.resolve(`${pkg}/package.json`));
}

function main() {
  rmSync(OUT_FONTS, { recursive: true, force: true });
  mkdirSync(OUT_FONTS, { recursive: true });

  const sections = [];
  const licenses = [];

  for (const { pkg } of FAMILIES) {
    const dir = resolvePkgDir(pkg);
    const meta = JSON.parse(readFileSync(join(dir, 'metadata.json'), 'utf8'));
    const family = meta.family; // e.g. "Figtree"
    const variableName = `${family} Variable`; // fontsource's registered name

    for (const cssName of AXIS_CSS) {
      const cssPath = join(dir, cssName);
      if (!existsSync(cssPath)) continue;
      let css = readFileSync(cssPath, 'utf8');

      // Copy every referenced woff2 into src/styles/fonts and repoint the url.
      const fileRe = /url\(\.\/files\/([^)]+\.woff2)\)/g;
      let match;
      while ((match = fileRe.exec(css)) !== null) {
        const fileName = match[1];
        copyFileSync(join(dir, 'files', fileName), join(OUT_FONTS, fileName));
      }
      css = css
        .replaceAll(`'${variableName}'`, `'${family}'`)
        .replace(/url\(\.\/files\/([^)]+\.woff2)\)/g, "url('./fonts/$1')");

      sections.push(`/* ${meta.family} — ${cssName} (from ${pkg}) */\n${css.trim()}`);
    }

    // Bundle the license next to the fonts (OFL requires distribution).
    const licenseSrc = existsSync(join(dir, 'LICENSE'))
      ? join(dir, 'LICENSE')
      : join(dir, 'LICENSE.md');
    if (existsSync(licenseSrc)) {
      const licName = `${meta.id}-LICENSE.txt`;
      copyFileSync(licenseSrc, join(OUT_FONTS, licName));
      licenses.push(`${meta.family}: fonts/${licName}`);
    }
  }

  const header = [
    '/*',
    ' * Harmony bundled fonts. GENERATED by scripts/sync-fonts.mjs — do not edit.',
    ' * Variable woff2 files live in ./fonts/. Imported by globals.css; family names',
    " * match the --font-* tokens in tokens.css ('Figtree', 'Lexend', 'JetBrains Mono').",
    ' *',
    ' * Licenses (SIL Open Font License 1.1):',
    ...licenses.map((l) => ` *   ${l}`),
    ' */',
    '',
  ].join('\n');

  writeFileSync(join(STYLES, 'fonts.css'), header + sections.join('\n\n') + '\n');
  console.log(`sync-fonts: wrote src/styles/fonts.css and ${OUT_FONTS}`);
}

main();
