#!/usr/bin/env node
/**
 * Flatten multi-product tokens into single-product builds + optional static kits.
 * Usage:
 *   node scripts/build-product.mjs <cp|vp|ppm|maconomy> [--static-only|--npm-only]
 *   node scripts/build-product.mjs --all [--static-only|--npm-only]
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  rmSync,
  existsSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const PRODUCTS = ['cp', 'vp', 'ppm', 'maconomy'];
const here = dirname(fileURLToPath(import.meta.url));
const PKG = join(here, '..');

function fail(msg) {
  console.error(`build-product: ${msg}`);
  process.exit(1);
}

function splitTopLevelBlocks(css) {
  const blocks = [];
  let depth = 0;
  let pending = '';
  let body = '';
  let selector = '';
  for (const ch of css) {
    if (ch === '{') {
      if (depth === 0) {
        selector = pending.trim();
        pending = '';
        body = '';
      } else {
        body += ch;
      }
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) {
        blocks.push({ selector, body });
        pending = '';
      } else {
        body += ch;
      }
    } else if (depth === 0) {
      pending += ch;
    } else {
      body += ch;
    }
  }
  return blocks;
}

function parseDeclarations(body, into) {
  const map = into ?? new Map();
  const clean = body.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const raw of clean.split(';')) {
    const part = raw.trim();
    if (!part) continue;
    const idx = part.indexOf(':');
    if (idx === -1) continue;
    const key = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (key.startsWith('--')) map.set(key, value);
  }
  return map;
}

function emitBlock(selector, map) {
  const lines = [...map.entries()].map(([k, v]) => `  ${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

function flattenTokens(css, product) {
  const blocks = splitTopLevelBlocks(css);
  const root = new Map();
  const dark = new Map();
  const passthrough = [];
  for (const { selector, body } of blocks) {
    const sel = selector.replace(/\/\*[\s\S]*?\*\//g, '').trim();
    if (sel === ':root') {
      parseDeclarations(body, root);
      continue;
    }
    if (sel === 'html.dark' || sel === '.dark') {
      parseDeclarations(body, dark);
      continue;
    }
    const data = sel.match(/^html\[data-product=['"]([a-z]+)['"]\](\.dark)?$/);
    if (data) {
      if (data[1] === product) parseDeclarations(body, data[2] ? dark : root);
      continue;
    }
    const theme = sel.match(/^html\.theme-([a-z]+)(\.dark)?$/);
    if (theme) {
      if (theme[1] === product) parseDeclarations(body, theme[2] ? dark : root);
      continue;
    }
    passthrough.push(`${selector.trim()} {${body}}`);
  }
  const parts = [
    `/* Harmony single-product build: ${product}. Generated by build-product.mjs — do not edit.`,
    `   Product is baked into :root/.dark; there is no product attribute or runtime switching. */`,
    '',
    emitBlock(':root', root),
  ];
  if (dark.size) parts.push('', emitBlock('.dark', dark));
  if (passthrough.length) parts.push('', ...passthrough);
  return parts.join('\n') + '\n';
}

function productBanner(product) {
  return [
    `> **Single-product build: \`${product}\`.** Import this product subpath (or unzip this product’s static kit) once.`,
    `> There is no runtime product switching. Toggle light/dark with \`document.documentElement.classList\` / \`setColorScheme\`.`,
    '',
  ].join('\n');
}

function writeProductDocs(outDir, product) {
  const agentsSrc = join(PKG, 'AGENTS.md');
  const llmsSrc = join(PKG, 'llms.txt');
  if (existsSync(agentsSrc)) {
    writeFileSync(join(outDir, 'AGENTS.md'), productBanner(product) + readFileSync(agentsSrc, 'utf8'));
  }
  if (existsSync(llmsSrc)) {
    writeFileSync(join(outDir, 'llms.txt'), productBanner(product) + readFileSync(llmsSrc, 'utf8'));
  }
  const docsSrc = join(PKG, 'docs');
  if (existsSync(docsSrc)) {
    cpSync(docsSrc, join(outDir, 'docs'), { recursive: true });
  }
  const cem = join(PKG, 'custom-elements.json');
  if (existsSync(cem)) cpSync(cem, join(outDir, 'custom-elements.json'));
}

function appendLayer(flatCss, relativePath, banner) {
  const filePath = join(PKG, relativePath);
  if (!existsSync(filePath)) fail(`missing ${filePath}`);
  const css = readFileSync(filePath, 'utf8').trim();
  return `${flatCss.trimEnd()}\n\n/* --- ${banner} --- */\n${css}\n`;
}

function appendReset(flatCss) {
  return appendLayer(flatCss, 'src/styles/reset.css', 'reset');
}

function appendTypography(flatCss) {
  return appendLayer(
    flatCss,
    'src/styles/typography.css',
    'typography (element defaults + role classes)',
  );
}

function appendButton(flatCss) {
  return appendLayer(flatCss, 'src/styles/button.css', 'button (native defaults + .btn)');
}

function appendCard(flatCss) {
  return appendLayer(flatCss, 'src/styles/card.css', 'card (BEM recipe)');
}

function appendLink(flatCss) {
  return appendLayer(flatCss, 'src/styles/link.css', 'link (muted + icon inherit)');
}

function appendLabel(flatCss) {
  return appendLayer(flatCss, 'src/styles/label.css', 'label (native recipe)');
}

function appendInput(flatCss) {
  return appendLayer(flatCss, 'src/styles/input.css', 'input/textarea (native defaults + wrappers)');
}

function appendInputCp(flatCss, product) {
  if (product !== 'cp') return flatCss;
  return appendLayer(flatCss, 'src/styles/input-cp.css', 'input CP compact + form-layout default');
}

function appendButtonGroup(flatCss) {
  return appendLayer(flatCss, 'src/styles/button-group.css', 'button-group (native/hybrid)');
}

function appendListMenu(flatCss) {
  return appendLayer(flatCss, 'src/styles/list-menu.css', 'list-menu (BEM recipe)');
}

function appendCompanyPickerDoc(flatCss) {
  return appendLayer(
    flatCss,
    'src/styles/company-picker-doc.css',
    'company-picker slotted options (document)',
  );
}

function appendUserMenuDoc(flatCss) {
  return appendLayer(
    flatCss,
    'src/styles/user-menu-doc.css',
    'user-menu slotted items (document)',
  );
}

function appendCheckbox(flatCss) {
  return appendLayer(flatCss, 'src/styles/checkbox.css', 'checkbox (native + BEM)');
}

function appendRadio(flatCss) {
  return appendLayer(flatCss, 'src/styles/radio.css', 'radio (native + BEM)');
}

function appendTable(flatCss) {
  return appendLayer(flatCss, 'src/styles/table.css', 'table (native + hybrid)');
}

function appendForcedColors(flatCss) {
  const forcedPath = join(PKG, 'src/styles/forced-colors.css');
  if (!existsSync(forcedPath)) fail(`missing ${forcedPath}`);
  const forced = readFileSync(forcedPath, 'utf8').trim();
  return `${flatCss.trimEnd()}\n\n/* --- forced-colors (Windows High Contrast) --- */\n${forced}\n`;
}

function writeElementModules(out, product) {
  const elementFiles = [
    'HarmonyElement.js',
    'HarmonyIcon.js',
    'HarmonyButton.js',
    'HarmonyCard.js',
    'HarmonyProgress.js',
    'HarmonySpinner.js',
    'HarmonyAccordion.js',
    'HarmonyAccordionItem.js',
    'HarmonyBadge.js',
    'HarmonyAvatar.js',
    'HarmonyChip.js',
    'HarmonyAlert.js',
    'HarmonyTooltip.js',
    'HarmonyDialog.js',
    'HarmonyInput.js',
    'HarmonyTextarea.js',
    'HarmonyFormLayout.js',
    'HarmonyFormRow.js',
    'HarmonySelect.js',
    'fieldLabel.js',
    'pickerDates.js',
    'HarmonyPickerPopup.js',
    'HarmonyDatePicker.js',
    'HarmonyTimePicker.js',
    'HarmonyDateTimePicker.js',
    'HarmonyMonthPicker.js',
    'HarmonyWeekPicker.js',
    'HarmonyDateInput.js',
    'HarmonyButtonGroup.js',
    'HarmonyListMenu.js',
    'HarmonyTable.js',
    'HarmonyNotificationBadge.js',
    'HarmonyCheckbox.js',
    'HarmonyRadio.js',
    'HarmonyToggle.js',
    'HarmonyTabStrip.js',
    'HarmonyShellHeader.js',
    'HarmonyLeftSidebar.js',
    'HarmonyRightSidebar.js',
    'HarmonyCompanyPicker.js',
    'HarmonyUserMenu.js',
    'leftSidebarDefaults.js',
    'rightSidebarDefaults.js',
  ];
  for (const file of elementFiles) {
    writeFileSync(join(out, file), readFileSync(join(PKG, 'src/elements', file), 'utf8'));
  }
  // Single-product logo asset (no other product logos in the kit)
  const logoByProduct = { cp: 'CPVPLogo', vp: 'CPVPLogo', ppm: 'PPMLogo', maconomy: 'MacLogo' };
  const logoName = logoByProduct[product] || 'CPVPLogo';
  const logoSrc = join(PKG, 'assets/logos', `${logoName}.svg`);
  if (!existsSync(logoSrc)) fail(`missing product logo ${logoSrc}`);
  const assetsOut = join(out, 'assets');
  mkdirSync(assetsOut, { recursive: true });
  cpSync(logoSrc, join(assetsOut, 'logo.svg'));
  writeFileSync(
    join(out, 'productLogo.js'),
    `/**
 * Product logo URL for this single-product kit.
 * Brand mark lives at ./assets/logo.svg — keep the kit folder intact.
 */

/** @type {string} */
export const PRODUCT_LOGO_ICON = '${logoName}';

/** @type {Record<string, string>} */
export const PRODUCT_LOGO_BY_ID = {
  ${product}: '${logoName}',
};

/**
 * @returns {string}
 */
export function resolveProductLogoKey() {
  return PRODUCT_LOGO_ICON;
}

/**
 * Absolute URL to this kit's logo SVG.
 * @returns {string}
 */
export function resolveProductLogoUrl() {
  return new URL('./assets/logo.svg', import.meta.url).href;
}
`,
  );
  // Left sidebar defaults: bake product id for the kit
  writeFileSync(
    join(out, 'leftSidebarDefaults.js'),
    readFileSync(join(PKG, 'src/elements/leftSidebarDefaults.js'), 'utf8').replace(
      "export const PRODUCT_LEFT_SIDEBAR_ID = 'cp';",
      `export const PRODUCT_LEFT_SIDEBAR_ID = '${product}';`,
    ),
  );
  writeFileSync(
    join(out, 'rightSidebarDefaults.js'),
    readFileSync(join(PKG, 'src/elements/rightSidebarDefaults.js'), 'utf8').replace(
      "export const PRODUCT_RIGHT_SIDEBAR_ID = 'cp';",
      `export const PRODUCT_RIGHT_SIDEBAR_ID = '${product}';`,
    ),
  );
  // Flattened layout: sheet helpers sit beside generated CSS modules.
  const sheetRewrites = [
    ['typography.js', '../styles/generated/typographyCss.js', './generated/typographyCss.js'],
    ['button.js', '../styles/generated/buttonCss.js', './generated/buttonCss.js'],
    ['card.js', '../styles/generated/cardCss.js', './generated/cardCss.js'],
    ['progress.js', '../styles/generated/progressCss.js', './generated/progressCss.js'],
    ['spinner.js', '../styles/generated/spinnerCss.js', './generated/spinnerCss.js'],
    ['accordion.js', '../styles/generated/accordionCss.js', './generated/accordionCss.js'],
    ['badge.js', '../styles/generated/badgeCss.js', './generated/badgeCss.js'],
    ['avatar.js', '../styles/generated/avatarCss.js', './generated/avatarCss.js'],
    ['chip.js', '../styles/generated/chipCss.js', './generated/chipCss.js'],
    ['link.js', '../styles/generated/linkCss.js', './generated/linkCss.js'],
    ['alert.js', '../styles/generated/alertCss.js', './generated/alertCss.js'],
    ['tooltip.js', '../styles/generated/tooltipCss.js', './generated/tooltipCss.js'],
    ['dialog.js', '../styles/generated/dialogCss.js', './generated/dialogCss.js'],
    ['input-field.js', '../styles/generated/inputFieldCss.js', './generated/inputFieldCss.js'],
    ['label.js', '../styles/generated/labelCss.js', './generated/labelCss.js'],
    ['input.js', '../styles/generated/inputCss.js', './generated/inputCss.js'],
    ['pickers.js', '../styles/generated/pickersCss.js', './generated/pickersCss.js'],
    ['button-group.js', '../styles/generated/buttonGroupCss.js', './generated/buttonGroupCss.js'],
    ['list-menu.js', '../styles/generated/listMenuCss.js', './generated/listMenuCss.js'],
    ['table.js', '../styles/generated/tableCss.js', './generated/tableCss.js'],
    ['checkbox.js', '../styles/generated/checkboxCss.js', './generated/checkboxCss.js'],
    ['radio.js', '../styles/generated/radioCss.js', './generated/radioCss.js'],
    ['toggle.js', '../styles/generated/toggleCss.js', './generated/toggleCss.js'],
    ['notification-badge.js', '../styles/generated/notificationBadgeCss.js', './generated/notificationBadgeCss.js'],
    ['tab-strip.js', '../styles/generated/tabStripCss.js', './generated/tabStripCss.js'],
    ['shell-header.js', '../styles/generated/shellHeaderCss.js', './generated/shellHeaderCss.js'],
    ['left-sidebar.js', '../styles/generated/leftSidebarCss.js', './generated/leftSidebarCss.js'],
    ['right-sidebar.js', '../styles/generated/rightSidebarCss.js', './generated/rightSidebarCss.js'],
    ['company-picker.js', '../styles/generated/companyPickerCss.js', './generated/companyPickerCss.js'],
    ['user-menu.js', '../styles/generated/userMenuCss.js', './generated/userMenuCss.js'],
  ];
  for (const [file, from, to] of sheetRewrites) {
    writeFileSync(
      join(out, file),
      readFileSync(join(PKG, 'src/elements', file), 'utf8').replaceAll(
        '../styles/generated/',
        './generated/',
      ),
    );
  }
  // Element modules import generated CSS from ../styles/generated — rewrite for flat dist.
  for (const el of [
    'HarmonyProgress.js',
    'HarmonySpinner.js',
    'HarmonyAccordion.js',
    'HarmonyAccordionItem.js',
    'HarmonyBadge.js',
    'HarmonyAvatar.js',
    'HarmonyChip.js',
    'HarmonyAlert.js',
    'HarmonyTooltip.js',
    'HarmonyDialog.js',
    'HarmonyInput.js',
    'HarmonyTextarea.js',
    'HarmonySelect.js',
    'HarmonyNotificationBadge.js',
    'HarmonyTabStrip.js',
    'HarmonyShellHeader.js',
    'HarmonyLeftSidebar.js',
    'HarmonyRightSidebar.js',
    'HarmonyCompanyPicker.js',
    'HarmonyUserMenu.js',
  ]) {
    writeFileSync(
      join(out, el),
      readFileSync(join(PKG, 'src/elements', el), 'utf8').replaceAll(
        '../styles/generated/',
        './generated/',
      ),
    );
  }
  cpSync(join(PKG, 'src/elements/generated'), join(out, 'generated'), { recursive: true });
  for (const css of [
    'typographyCss.js',
    'buttonCss.js',
    'cardCss.js',
    'progressCss.js',
    'spinnerCss.js',
    'accordionCss.js',
    'accordionItemCss.js',
    'badgeCss.js',
    'avatarCss.js',
    'chipCss.js',
    'linkCss.js',
    'alertCss.js',
    'tooltipCss.js',
    'dialogCss.js',
    'inputFieldCss.js',
    'labelCss.js',
    'inputCss.js',
    'pickersCss.js',
    'buttonGroupCss.js',
    'listMenuCss.js',
    'tableCss.js',
    'checkboxCss.js',
    'radioCss.js',
    'toggleCss.js',
    'notificationBadgeCss.js',
    'tabStripCss.js',
    'shellHeaderCss.js',
    'leftSidebarCss.js',
    'rightSidebarCss.js',
    'companyPickerCss.js',
    'userMenuCss.js',
  ]) {
    cpSync(join(PKG, 'src/styles/generated', css), join(out, 'generated', css));
  }
}

function buildOne(product, { npm, staticKit }) {
  const tokensPath = join(PKG, 'src/styles/tokens.css');
  if (!existsSync(tokensPath)) fail(`missing ${tokensPath}`);
  const flatCss = appendForcedColors(
    appendTable(
      appendRadio(
        appendCheckbox(
          appendCompanyPickerDoc(
            appendUserMenuDoc(
              appendListMenu(
                appendButtonGroup(
                  appendInputCp(
                    appendInput(
                      appendLabel(
                        appendLink(
                          appendCard(
                            appendButton(
                              appendTypography(
                                appendReset(flattenTokens(readFileSync(tokensPath, 'utf8'), product)),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    product,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );

  const elementsEntry = [
    `/* Harmony elements — product ${product} (relative imports for static + npm dist). */`,
    `export { HarmonyElement, createSheet, HarmonyIcon, HarmonyButton, HarmonyCard, HarmonyProgress, HarmonySpinner, HarmonyAccordion, HarmonyAccordionItem, HarmonyBadge, HarmonyAvatar, HarmonyChip, HarmonyAlert, HarmonyTooltip, HarmonyDialog, HarmonyInput, HarmonyTextarea, HarmonySelect, HarmonyFormLayout, HarmonyFormRow, HarmonyPickerPopup, HarmonyDatePicker, HarmonyTimePicker, HarmonyDateTimePicker, HarmonyMonthPicker, HarmonyWeekPicker, HarmonyDateInput, HarmonyButtonGroup, HarmonyListMenu, HarmonyTable, HarmonyNotificationBadge, HarmonyCheckbox, HarmonyRadio, HarmonyToggle, HarmonyTabStrip, HarmonyShellHeader, HarmonyLeftSidebar, HarmonyRightSidebar, HarmonyCompanyPicker, HarmonyUserMenu, registerIcons, registerHarmonyElements, typographySheet, typographyCss, buttonSheet, buttonCss, cardSheet, cardCss, progressSheet, progressCss, spinnerSheet, spinnerCss, accordionSheet, accordionItemSheet, accordionCss, accordionItemCss, badgeSheet, badgeCss, avatarSheet, avatarCss, chipSheet, chipCss, linkSheet, linkCss, alertSheet, alertCss, tooltipSheet, tooltipCss, dialogSheet, dialogCss, inputFieldSheet, inputFieldCss, labelSheet, labelCss, inputSheet, inputCss, pickersSheet, pickersCss, buttonGroupSheet, buttonGroupCss, listMenuSheet, listMenuCss, tableSheet, tableCss, notificationBadgeSheet, notificationBadgeCss, checkboxSheet, checkboxCss, radioSheet, radioCss, toggleSheet, toggleCss, tabStripSheet, tabStripCss, shellHeaderSheet, shellHeaderCss, leftSidebarSheet, leftSidebarCss, rightSidebarSheet, rightSidebarCss, companyPickerSheet, companyPickerCss, userMenuSheet, userMenuCss } from './register.js';`,
    `export {`,
    `  setColorScheme,`,
    `  getColorScheme,`,
    `  toggleColorScheme,`,
    `  initColorScheme,`,
    `  persistColorScheme,`,
    `  clearPersistedColorScheme,`,
    `  getPersistedColorScheme,`,
    `  COLOR_SCHEME_STORAGE_KEY,`,
    `} from './theme.js';`,
    `export {`,
    `  setDateTimeDefaults,`,
    `  getDateTimeDefaults,`,
    `  initDateTimeDefaults,`,
    `  setDateTimeAdapter,`,
    `  getDateTimeAdapter,`,
    `  getDateValue,`,
    `  setDateValue,`,
    `  getMachineValue,`,
    `  setMachineValue,`,
    `  formatDisplay,`,
    `  resolveLocale,`,
    `  resolveTimeFormat,`,
    `  subscribeDateTimeDefaults,`,
    `  createNativeAdapter,`,
    `  DATETIME_DEFAULTS_EVENT,`,
    `  LOCALE_ATTR,`,
    `  TIME_FORMAT_ATTR,`,
    `} from './datetime.js';`,
    `export { registerHarmonyElements as default } from './register.js';`,
  ].join('\n') + '\n';

  // Shared relative modules copied into each product out dir
  const themeJs = readFileSync(join(PKG, 'src/theme/index.js'), 'utf8');
  const datetimeJs = readFileSync(join(PKG, 'src/datetime/index.js'), 'utf8').replaceAll(
    '../elements/pickerDates.js',
    './pickerDates.js',
  );
  const registerStub = readFileSync(join(PKG, 'src/elements/index.js'), 'utf8');

  if (npm) {
    const out = join(PKG, 'dist-products', product);
    rmSync(out, { recursive: true, force: true });
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'styles.css'), flatCss);
    writeElementModules(out, product);
    writeFileSync(join(out, 'theme.js'), themeJs);
    writeFileSync(join(out, 'datetime.js'), datetimeJs);
    writeFileSync(join(out, 'register.js'), registerStub);
    writeFileSync(join(out, 'elements.js'), registerStub);
    writeFileSync(join(out, 'index.js'), elementsEntry);
    writeProductDocs(out, product);
    console.log(`npm product → ${out}`);
  }

  if (staticKit) {
    const out = join(PKG, 'dist-static', product);
    rmSync(out, { recursive: true, force: true });
    mkdirSync(out, { recursive: true });
    writeFileSync(join(out, 'styles.css'), flatCss);
    writeElementModules(out, product);
    writeFileSync(join(out, 'theme.js'), themeJs);
    writeFileSync(join(out, 'datetime.js'), datetimeJs);
    writeFileSync(
      join(out, 'elements.js'),
      [
        `import { registerHarmonyElements } from './register.js';`,
        `import {`,
        `  setColorScheme,`,
        `  getColorScheme,`,
        `  toggleColorScheme,`,
        `  initColorScheme,`,
        `  persistColorScheme,`,
        `  clearPersistedColorScheme,`,
        `  getPersistedColorScheme,`,
        `  COLOR_SCHEME_STORAGE_KEY,`,
        `} from './theme.js';`,
        `import {`,
        `  setDateTimeDefaults,`,
        `  getDateTimeDefaults,`,
        `  initDateTimeDefaults,`,
        `  setDateTimeAdapter,`,
        `  getDateTimeAdapter,`,
        `  getDateValue,`,
        `  setDateValue,`,
        `  getMachineValue,`,
        `  setMachineValue,`,
        `  formatDisplay,`,
        `  resolveLocale,`,
        `  resolveTimeFormat,`,
        `  subscribeDateTimeDefaults,`,
        `  createNativeAdapter,`,
        `  DATETIME_DEFAULTS_EVENT,`,
        `  LOCALE_ATTR,`,
        `  TIME_FORMAT_ATTR,`,
        `} from './datetime.js';`,
        `export { HarmonyElement, createSheet, HarmonyIcon, HarmonyButton, HarmonyCard, HarmonyProgress, HarmonySpinner, HarmonyAccordion, HarmonyAccordionItem, HarmonyBadge, HarmonyAvatar, HarmonyChip, HarmonyAlert, HarmonyTooltip, HarmonyDialog, HarmonyInput, HarmonyTextarea, HarmonySelect, HarmonyFormLayout, HarmonyFormRow, HarmonyPickerPopup, HarmonyDatePicker, HarmonyTimePicker, HarmonyDateTimePicker, HarmonyMonthPicker, HarmonyWeekPicker, HarmonyDateInput, HarmonyButtonGroup, HarmonyListMenu, HarmonyTable, HarmonyNotificationBadge, HarmonyCheckbox, HarmonyRadio, HarmonyToggle, HarmonyTabStrip, HarmonyShellHeader, HarmonyLeftSidebar, HarmonyRightSidebar, HarmonyCompanyPicker, HarmonyUserMenu, registerIcons, typographySheet, typographyCss, buttonSheet, buttonCss, cardSheet, cardCss, progressSheet, progressCss, spinnerSheet, spinnerCss, accordionSheet, accordionItemSheet, accordionCss, accordionItemCss, badgeSheet, badgeCss, avatarSheet, avatarCss, chipSheet, chipCss, linkSheet, linkCss, alertSheet, alertCss, tooltipSheet, tooltipCss, dialogSheet, dialogCss, inputFieldSheet, inputFieldCss, labelSheet, labelCss, inputSheet, inputCss, pickersSheet, pickersCss, buttonGroupSheet, buttonGroupCss, listMenuSheet, listMenuCss, tableSheet, tableCss, notificationBadgeSheet, notificationBadgeCss, checkboxSheet, checkboxCss, radioSheet, radioCss, toggleSheet, toggleCss, tabStripSheet, tabStripCss, shellHeaderSheet, shellHeaderCss, leftSidebarSheet, leftSidebarCss, rightSidebarSheet, rightSidebarCss, companyPickerSheet, companyPickerCss, userMenuSheet, userMenuCss } from './register.js';`,
        `export {`,
        `  registerHarmonyElements,`,
        `  setColorScheme,`,
        `  getColorScheme,`,
        `  toggleColorScheme,`,
        `  initColorScheme,`,
        `  persistColorScheme,`,
        `  clearPersistedColorScheme,`,
        `  getPersistedColorScheme,`,
        `  COLOR_SCHEME_STORAGE_KEY,`,
        `  setDateTimeDefaults,`,
        `  getDateTimeDefaults,`,
        `  initDateTimeDefaults,`,
        `  setDateTimeAdapter,`,
        `  getDateTimeAdapter,`,
        `  getDateValue,`,
        `  setDateValue,`,
        `  getMachineValue,`,
        `  setMachineValue,`,
        `  formatDisplay,`,
        `  resolveLocale,`,
        `  resolveTimeFormat,`,
        `  subscribeDateTimeDefaults,`,
        `  createNativeAdapter,`,
        `  DATETIME_DEFAULTS_EVENT,`,
        `  LOCALE_ATTR,`,
        `  TIME_FORMAT_ATTR,`,
        `};`,
        `registerHarmonyElements();`,
      ].join('\n') + '\n',
    );
    writeFileSync(
      join(out, 'register.js'),
      registerStub,
    );
    writeProductDocs(out, product);
    writeFileSync(
      join(out, 'README.md'),
      `# Harmony Design System — Vanilla (${product})

Static drop-in (no npm). Copy this folder into your site (e.g. \`/vendor/harmony/\`). Keep \`assets/\` with the kit — Shell Header loads \`assets/logo.svg\`.

\`\`\`html
<link rel="stylesheet" href="/vendor/harmony/styles.css" />
<script type="module" src="/vendor/harmony/elements.js"></script>
<!-- Custom elements register as they are converted; until then this kit ships tokens + base helpers. -->
\`\`\`

Toggle dark mode: \`document.documentElement.classList.toggle('dark')\` or import \`setColorScheme\` from \`./theme.js\`.

Product is **this folder** — do not switch products at runtime.
`,
    );

    const zipName = `harmony-design-system-vanilla-${product}.zip`;
    const zipPath = join(PKG, 'dist-static', zipName);
    if (existsSync(zipPath)) rmSync(zipPath);
    // Prefer tar/zip via PowerShell Compress-Archive on Windows
    const ps = spawnSync(
      'powershell',
      ['-NoProfile', '-Command', `Compress-Archive -Path '${out}\\*' -DestinationPath '${zipPath}' -Force`],
      { encoding: 'utf8' },
    );
    if (ps.status !== 0) {
      console.warn(`zip skipped for ${product}: ${ps.stderr || ps.stdout || 'Compress-Archive failed'}`);
    } else {
      console.log(`static zip → ${zipPath}`);
    }
    console.log(`static kit → ${out}`);
  }
}

const args = process.argv.slice(2);
const all = args.includes('--all');
const staticOnly = args.includes('--static-only');
const npmOnly = args.includes('--npm-only');
const npm = !staticOnly;
const staticKit = !npmOnly;
const products = all
  ? PRODUCTS
  : args.filter((a) => !a.startsWith('--'));

if (!products.length) fail('usage: build-product.mjs <product|--all> [--static-only|--npm-only]');

for (const p of products) {
  if (!PRODUCTS.includes(p)) fail(`unknown product: ${p}`);
  buildOne(p, { npm, staticKit });
}
