#!/usr/bin/env node
/**
 * Build the self-contained Icon registries.
 * Heroicons remain a build-only dependency; Harmony custom SVGs come from the
 * reference public directory. Generated modules are intentionally committed so
 * package source and the demo work immediately after install.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');
const repo = join(pkg, '..', '..', '..', '..');
const heroDir = join(pkg, '..', '..', 'node_modules', 'heroicons', '24', 'outline');
const publicDir = join(repo, 'public');
const outputDir = join(pkg, 'src', 'elements', 'generated');
const demoOutput = join(pkg, '..', '..', 'apps', 'demo', 'src', 'demo', 'generated', 'iconNames.js');

function svgFiles(directory) {
  return readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory() ? svgFiles(path) : extname(entry.name).toLowerCase() === '.svg' ? [path] : [];
    })
    .sort((a, b) => a.localeCompare(b));
}

function normalizeSvg(source) {
  return source
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s(?:width|height)="[^"]*"/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeCustomSvg(source) {
  return normalizeSvg(source).replace(
    /\s(fill|stroke)="(?!none\b|currentColor\b|url\()[^"]+"/gi,
    ' $1="currentColor"',
  );
}

function registry(files, normalize = normalizeSvg) {
  return Object.fromEntries(
    files.map((file) => [basename(file, '.svg'), normalize(readFileSync(file, 'utf8'))]),
  );
}

function moduleText(name, value, source) {
  return `/* Generated by scripts/generate-icons.mjs from ${source}. Do not edit. */\n` +
    `export const ${name} = Object.freeze(${JSON.stringify(value, null, 2)});\n`;
}

const hero = registry(svgFiles(heroDir));
const custom = registry(svgFiles(publicDir), normalizeCustomSvg);

mkdirSync(outputDir, { recursive: true });
writeFileSync(
  join(outputDir, 'heroIcons.js'),
  moduleText('heroIcons', hero, relative(repo, heroDir).replaceAll('\\', '/')),
);
writeFileSync(
  join(outputDir, 'customIcons.js'),
  moduleText('customIcons', custom, 'reference public SVG files'),
);

mkdirSync(dirname(demoOutput), { recursive: true });
writeFileSync(
  demoOutput,
  `/* Generated by packages/ui/scripts/generate-icons.mjs. Do not edit. */\n` +
    `export const heroIconNames = Object.freeze(${JSON.stringify(Object.keys(hero), null, 2)});\n` +
    `export const customIconNames = Object.freeze(${JSON.stringify(Object.keys(custom), null, 2)});\n`,
);

console.log(`Generated ${Object.keys(hero).length} Heroicons and ${Object.keys(custom).length} Harmony custom icons.`);
