#!/usr/bin/env node
/**
 * Mirror CSS layers into ESM string modules for Shadow DOM adoption.
 *
 * Custom Elements adopt the same rules inside Shadow DOM, and the static kit
 * runs without a bundler — so the CSS has to reach JS as a plain module rather
 * than a `?raw` / CSS-module import. Generated files are committed so package
 * source and the demo work immediately after install.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputDir = join(pkg, 'src', 'styles', 'generated');
mkdirSync(outputDir, { recursive: true });

function escapeCss(css) {
  return css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function writeModule(fileName, exportName, sources, header) {
  const css = sources.map((s) => readFileSync(s, 'utf8').trim()).join('\n\n') + '\n';
  const output = join(outputDir, fileName);
  writeFileSync(
    output,
    `/* Generated by scripts/generate-styles.mjs ${header} — do not edit. */\nexport const ${exportName} = \`${escapeCss(css)}\`;\n`,
    'utf8',
  );
  console.log(`Generated ${exportName} (${css.length} chars).`);
}

writeModule(
  'typographyCss.js',
  'typographyCss',
  [join(pkg, 'src', 'styles', 'reset.css'), join(pkg, 'src', 'styles', 'typography.css')],
  'from src/styles/reset.css + typography.css',
);

writeModule(
  'buttonCss.js',
  'buttonCss',
  [join(pkg, 'src', 'styles', 'button.css')],
  'from src/styles/button.css',
);

writeModule(
  'cardCss.js',
  'cardCss',
  [join(pkg, 'src', 'styles', 'card.css')],
  'from src/styles/card.css',
);

writeModule(
  'progressCss.js',
  'progressCss',
  [join(pkg, 'src', 'styles', 'progress.css')],
  'from src/styles/progress.css',
);

writeModule(
  'spinnerCss.js',
  'spinnerCss',
  [join(pkg, 'src', 'styles', 'spinner.css')],
  'from src/styles/spinner.css',
);

writeModule(
  'badgeCss.js',
  'badgeCss',
  [join(pkg, 'src', 'styles', 'badge.css')],
  'from src/styles/badge.css',
);

writeModule(
  'avatarCss.js',
  'avatarCss',
  [join(pkg, 'src', 'styles', 'avatar.css')],
  'from src/styles/avatar.css',
);

writeModule(
  'chipCss.js',
  'chipCss',
  [join(pkg, 'src', 'styles', 'chip.css')],
  'from src/styles/chip.css',
);

writeModule(
  'linkCss.js',
  'linkCss',
  [join(pkg, 'src', 'styles', 'link.css')],
  'from src/styles/link.css',
);

writeModule(
  'alertCss.js',
  'alertCss',
  [join(pkg, 'src', 'styles', 'alert.css')],
  'from src/styles/alert.css',
);

writeModule(
  'tooltipCss.js',
  'tooltipCss',
  [join(pkg, 'src', 'styles', 'tooltip.css')],
  'from src/styles/tooltip.css',
);

writeModule(
  'dialogCss.js',
  'dialogCss',
  [join(pkg, 'src', 'styles', 'dialog.css')],
  'from src/styles/dialog.css',
);

writeModule(
  'inputFieldCss.js',
  'inputFieldCss',
  [join(pkg, 'src', 'styles', 'input-field.css')],
  'from src/styles/input-field.css',
);

writeModule(
  'labelCss.js',
  'labelCss',
  [join(pkg, 'src', 'styles', 'label.css')],
  'from src/styles/label.css',
);

writeModule(
  'inputCss.js',
  'inputCss',
  [join(pkg, 'src', 'styles', 'input.css')],
  'from src/styles/input.css',
);

writeModule(
  'pickersCss.js',
  'pickersCss',
  [join(pkg, 'src', 'styles', 'pickers.css')],
  'from src/styles/pickers.css',
);

writeModule(
  'buttonGroupCss.js',
  'buttonGroupCss',
  [join(pkg, 'src', 'styles', 'button-group.css')],
  'from src/styles/button-group.css',
);

writeModule(
  'listMenuCss.js',
  'listMenuCss',
  [join(pkg, 'src', 'styles', 'list-menu.css')],
  'from src/styles/list-menu.css',
);

writeModule(
  'checkboxCss.js',
  'checkboxCss',
  [join(pkg, 'src', 'styles', 'checkbox.css')],
  'from src/styles/checkbox.css',
);

writeModule(
  'radioCss.js',
  'radioCss',
  [join(pkg, 'src', 'styles', 'radio.css')],
  'from src/styles/radio.css',
);

writeModule(
  'toggleCss.js',
  'toggleCss',
  [join(pkg, 'src', 'styles', 'toggle.css')],
  'from src/styles/toggle.css',
);

writeModule(
  'notificationBadgeCss.js',
  'notificationBadgeCss',
  [join(pkg, 'src', 'styles', 'notification-badge.css')],
  'from src/styles/notification-badge.css',
);

writeModule(
  'tabStripCss.js',
  'tabStripCss',
  [join(pkg, 'src', 'styles', 'tab-strip.css')],
  'from src/styles/tab-strip.css',
);

writeModule(
  'shellHeaderCss.js',
  'shellHeaderCss',
  [join(pkg, 'src', 'styles', 'shell-header.css')],
  'from src/styles/shell-header.css',
);

writeModule(
  'leftSidebarCss.js',
  'leftSidebarCss',
  [join(pkg, 'src', 'styles', 'left-sidebar.css')],
  'from src/styles/left-sidebar.css',
);

writeModule(
  'rightSidebarCss.js',
  'rightSidebarCss',
  [join(pkg, 'src', 'styles', 'right-sidebar.css')],
  'from src/styles/right-sidebar.css',
);

writeModule(
  'companyPickerCss.js',
  'companyPickerCss',
  [join(pkg, 'src', 'styles', 'company-picker.css')],
  'from src/styles/company-picker.css',
);

writeModule(
  'userMenuCss.js',
  'userMenuCss',
  [join(pkg, 'src', 'styles', 'user-menu.css')],
  'from src/styles/user-menu.css',
);

writeModule(
  'accordionCss.js',
  'accordionCss',
  [join(pkg, 'src', 'styles', 'accordion.css')],
  'from src/styles/accordion.css',
);

writeModule(
  'accordionItemCss.js',
  'accordionItemCss',
  [join(pkg, 'src', 'styles', 'accordion-item.css')],
  'from src/styles/accordion-item.css',
);

writeModule(
  'tableCss.js',
  'tableCss',
  [join(pkg, 'src', 'styles', 'table.css')],
  'from src/styles/table.css',
);
